FSVentasCoreAs/FSVentasCoreAs/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FSVentasCoreAs.DAL;
using FSVentasCoreAs.Models;
using Microsoft.AspNetCore.Authorization;
using FSVentasCoreAs.Models.Dirreciones;
using FSVentasCoreAs.BLL;

namespace FSVentasCoreAs.Controllers
{
    [Authorize(ActiveAuthenticationSchemes = "CookiePolicy")]
    public class ClientesController : Controller
    {
        private readonly FSVentasCoreDb _context;
        private FSVentasCoreDb db = new FSVentasCoreDb();

        public ClientesController(FSVentasCoreDb context)
        {
            _context = context;    
        }
        public async Task<IActionResult> Index()
        {
            var fSVentasCoreDb = _context.Clientes.Include(c => c.DistritosMunicipales).Include(c => c.Municipios).Include(c => c.Provincias).Include(c => c.Sectores);
            return View(await fSVentasCoreDb.ToListAsync());
        }
        // GET: Clientes
        public async Task<IActionResult> Consulta()
        {
            var fSVentasCoreDb = _context.Clientes.Include(c => c.DistritosMunicipales).Include(c => c.Municipios).Include(c => c.Provincias).Include(c => c.Sectores);
            return View(await fSVentasCoreDb.ToListAsync());
        }
        // GET: Clientes/Details/5
        public async Task<IActionResult> Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientes = await _context.Clientes
                .Include(c => c.DistritosMunicipales)
                .Include(c => c.Municipios)
                .Include(c => c.Provincias)
                .Include(c => c.Sectores)
                .SingleOrDefaultAsync(m => m.ClienteId == id);
            if (clientes == null)
            {
                return NotFound();
            }

            return View(clientes);
        }

        // GET: Clientes/Create
        public IActionResult Crear()
        {
            List<Provincias> lstProvincia = db.Provincias.ToList();
            lstProvincia.Insert(0, new Provincias { ProvinciaId = 0, Nombre = "--Select Provincia--" });
            ViewBag.ProvinciaId = new SelectList(lstProvincia, "ProvinciaId", "Nombre");
            List<Municipios> lstMunicipios = db.Municipios.ToList();
            ViewBag.MunicipioId = new SelectList(lstMunicipios, "MunicipioId", "Nombre");
            List<DistritosMunicipales> lstDistrito = db.DistritosMunicipales.ToList();
            ViewBag.DistritoId = new SelectList(lstDistrito, "DistritoId", "Nombre");
            List<Sectores> lstSectores = db.Sectores.ToList();
            ViewBag.SectorId = new SelectList(lstSectores, "SectorId", "Nombre");


            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear([Bind("ClienteId,Nombre,Sexo,Cedula,ProvinciaId,MunicipioId,DistritoId,SectorId,Direccion,Telefono,Celular,Fecha")] Clientes clientes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clientes);
                await _context.SaveChangesAsync();
                return RedirectToAction("Consulta");
            }
            ViewData["DistritoId"] = new SelectList(_context.DistritosMunicipales, "DistritoId", "Nombre", clientes.DistritoId);
            ViewData["MunicipioId"] = new SelectList(_context.Municipios, "MunicipioId", "Nombre", clientes.MunicipioId);
            ViewData["ProvinciaId"] = new SelectList(_context.Provincias, "ProvinciaId", "Nombre", clientes.ProvinciaId);
            ViewData["SectorId"] = new SelectList(_context.Sectores, "SectorId", "Nombre", clientes.SectorId);
            return View(clientes);
        }
        [HttpGet]
        public JsonResult Lista(int? id)
        {
            var listado = BLL.ClientesBLL.GetLista();

            return Json(listado);
        }
        public JsonResult GetMunicipiosByProvinciaId(int id)
        {
            List<Municipios> municipios = new List<Municipios>();
            if (id > 0)
            {
                municipios = db.Municipios.Where(p => p.ProvinciaId == id).ToList();


            }
            else
            {
                municipios.Insert(0, new Municipios { MunicipioId = 0, Nombre = "--Selecionar Municipios --" });
            }
            var result = (from r in municipios
                          select new
                          {
                              municipioId = r.MunicipioId,
                              nombre = r.Nombre
                          }).ToList();

            return Json(result);

            // return Json(result);

        }

        public JsonResult GetdistritoIdByMunicipioId(int id)
        {
            List<DistritosMunicipales> distrito = new List<DistritosMunicipales>();
            if (id > 0)
            {
                distrito = db.DistritosMunicipales.Where(p => p.MunicipioId == id).ToList();

            }
            else
            {
                distrito.Insert(0, new DistritosMunicipales { DistritoId = 0, Nombre = "--Seleccionar Distritos Municipales--" });
            }
            var result = (from r in distrito
                          select new
                          {
                              distritoId = r.DistritoId,
                              nombre = r.Nombre
                          }).ToList();

            return Json(result);
            // return Json(result);

        }
        public JsonResult GetSectoresIdByDistritoId(int id)
        {
            List<Sectores> sectores = new List<Sectores>();
            if (id > 0)
            {
                sectores = db.Sectores.Where(p => p.DistritoId == id).ToList();

            }
            else
            {
                sectores.Insert(0, new Sectores { SectorId = 0, Nombre = "--Selecionar  Sectores " });
            }
            var result = (from r in sectores
                          select new
                          {
                              sectorId = r.SectorId,
                              nombre = r.Nombre
                          }).ToList();

            return Json(result);
            // return Json(result);

        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientes = await _context.Clientes.SingleOrDefaultAsync(m => m.ClienteId == id);
            if (clientes == null)
            {
                return NotFound();
            }
            ViewData["DistritoId"] = new SelectList(_context.DistritosMunicipales, "DistritoId", "Nombre", clientes.DistritoId);
            ViewData["MunicipioId"] = new SelectList(_context.Municipios, "MunicipioId", "Nombre", clientes.MunicipioId);
            ViewData["ProvinciaId"] = new SelectList(_context.Provincias, "ProvinciaId", "Nombre", clientes.ProvinciaId);
            ViewData["SectorId"] = new SelectList(_context.Sectores, "SectorId", "Nombre", clientes.SectorId);
            return View(clientes);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClienteId,Nombre,Sexo,Cedula,ProvinciaId,MunicipioId,DistritoId,SectorId,Direccion,Telefono,Celular,Fecha")] Clientes clientes)
        {
            if (id != clientes.ClienteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clientes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientesExists(clientes.ClienteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Consulta");
            }
            ViewData["DistritoId"] = new SelectList(_context.DistritosMunicipales, "DistritoId", "Nombre", clientes.DistritoId);
            ViewData["MunicipioId"] = new SelectList(_context.Municipios, "MunicipioId", "Nombre", clientes.MunicipioId);
            ViewData["ProvinciaId"] = new SelectList(_context.Provincias, "ProvinciaId", "Nombre", clientes.ProvinciaId);
            ViewData["SectorId"] = new SelectList(_context.Sectores, "SectorId", "Nombre", clientes.SectorId);
            return View(clientes);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientes = await _context.Clientes
                .Include(c => c.DistritosMunicipales)
                .Include(c => c.Municipios)
                .Include(c => c.Provincias)
                .Include(c => c.Sectores)
                .SingleOrDefaultAsync(m => m.ClienteId == id);
            if (clientes == null)
            {
                return NotFound();
            }

            return View(clientes);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]

FSVentasCoreAs/FSVentasCoreAs/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FSVentasCoreAs.DAL;
using FSVentasCoreAs.Models;
using FSVentasCoreAs.BLL;

namespace FSVentasCoreAs.Controllers
{
    public class VentasController : Controller
    {
        private readonly FSVentasCoreDb _context;

        public VentasController(FSVentasCoreDb context)
        {
            _context = context;    
        }
        [HttpPost]
        public JsonResult Modificar(ClasesDetalle venta)
        {
            var existe = (BLL.VentasBLL.Buscarr(venta.Encabezado.VentaId) != null);
            if (existe)
            {
                existe = BLL.VentasBLL.Modificar(venta);
                return Json(existe);
            }
            else
            {
                return Json(null);
            }
        }
        [HttpGet]
        public JsonResult LastIndex()
        {
            int id = VentasBLL.Identity();
            if (id > 1 || VentasBLL.Listar().Count > 0)
                ++id;
            return Json(id);
        }


        [HttpPost]
        public JsonResult Eliminar(ClasesDetalle venta)
        {
            var existe = (BLL.VentasBLL.BuscarEncabezado(venta.Encabezado.VentaId) != null);

            if (existe)
            {
                existe = BLL.VentasBLL.Eliminar(venta);
                return Json(existe);
            }
            else
            {
                return Json(null);
            }
        }
        [HttpGet]
        public ActionResult Buscar(int Id)
        {
            Ventas var = BLL.VentasBLL.Buscar(Id);

            return Json(var);
        }
        [HttpGet]
        public JsonResult  BuscarV(int ventaId)
        {
            Ventas venta = VentasBLL.Buscar(ventaId);
            return Json(venta);
        }
        public IActionResult Index()
        {
            return View(BLL.VentasBLL.Listar());
        }
        // GET: Facturas
        public IActionResult Consulta()
        {
            return View(BLL.VentasBLL.Listar());
        }

       

        // GET: Ventas/Details/5
        public async Task<IActionResult> Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ventas = await _context.Ventas
                .SingleOrDefaultAsync(m => m.VentaId == id);
            if (ventas == null)
            {
                return NotFound();
            }

            return View(ventas);
        }

        // GET: Ventas/Create
        public IActionResult Crear()
        {
            return View();
        }

        // POST: Ventas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear([Bind("VentaId,ArticuloId,articulo,Cantidad,Fecha,Total")] Ventas ventas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ventas);
                await _context.SaveChangesAsync();
                return RedirectToAction("Consulta");
            }
            return View(ventas);
        }

        // GET: Ventas/Edit/5
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ventas = await _context.Ventas.SingleOrDefaultAsync(m => m.VentaId == id);
            if (ventas == null)
            {
                return NotFound();
            }
            return View(ventas);
        }

        // POST: Ventas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, [Bind("VentaId,ArticuloId,articulo,Cantidad,Fecha,Total")] Ventas ventas)
        {
            if (id != ventas.VentaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ventas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VentasExists(ventas.VentaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Consulta");
            }
            return View(ventas);
        }

        // GET: Ventas/Delete/5
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ventas = await _context.Ventas
                .SingleOrDefaultAsync(m => m.VentaId == id);
            if (ventas == null)
            {
                return NotFound();
            }

            return View(ventas);
        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ventas = await _context.Ventas.SingleOrDefaultAsync(m => m.VentaId == id);
            _context.Ventas.Remove(ventas);
            await _context.SaveChangesAsync();
            return RedirectToAction("Consulta");
        }

        private bool VentasExists(int id)
        {
            return _context.Ventas.Any(e => e.VentaId == id);
        }
    }
}

FSVentasCoreAs/FSVentasCoreAs/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FSVentasCoreAs</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FSVentasCoreAs</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Registros <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            @if (Context.Session.GetString("UsuarioId") != null)
                            {

                                <li><a asp-area="" asp-controller="Usuarios" asp-action="Crear">Usurios</a></li>
                                <li><a asp-area="" asp-controller="TipoUsuarios" asp-action="Crear">Tipo de Usuarios</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="Articulos" asp-action="Crear">Articulos</a></li>
                                <li><a asp-area="" asp-controller="CategoriasArticulos" asp-action="Crear">Categorias</a></li>
                                <li><a asp-area="" asp-controller="MarcasArticulos" asp-action="Crear">Marcas</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="Proveedores" asp-action="Crear">Proveedores</a></li>
                                <li><a asp-area="" asp-controller="Clientes" asp-action="Crear">Clientes</a></li>
                                <li><a asp-area="" asp-controller="Empleados" asp-action="Crear">Empleados</a></li>
                                <li class="divider"></li>
                                <li class="Dirreciones"></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="Provincias" asp-action="Crear">Provincias</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="Municipios" asp-action="Crear">Municipios</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="DistritosMunicipales" asp-action="Crear">DistritosMunicipales</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="Sectores" asp-action="Crear">Sectores</a></li>
                                <li class="divider"></li>
                                <li><a asp-area="" asp-controller="Ventas" asp-action="Crear">Ventas</a></li>
                                <li><a asp-area="" asp-controller="VentasDetalles" asp-action="Crear">VentasDetalles</a></li>
                                <li class="divider"></li>
                            }
                            else
                            {
                                <li><a asp-area="" asp-controller="Home" asp-action="InicioSeccion">Inicio Seccion</a></li>


                            }

                        </ul>


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Consultas <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Usuarios" asp-action="Consulta">Usuarios</a></li>
                            <li><a asp-area="" asp-controller="TipoUsuarios" asp-action="Consulta">Tipo de Usuarios</a></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="Articulos" asp-action="Consulta">Articulos</a></li>
                            <li><a asp-area="" asp-controller="CategoriasArticulos" asp-action="Consulta">Categorias</a></li>
                            <li><a asp-area="" asp-controller="MarcasArticulos" asp-action="Index">Marcas</a></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="Proveedores" asp-action="Consulta">Proveedores</a></li>
                            <li><a asp-area="" asp-controller="Empleados" asp-action="Consulta">Empleados</a></li>=
                            <li><a asp-area="" asp-controller="Clientes" asp-action="Consulta">Clientes</a></li>
                            <li class="divider"></li>
                            <li class="Dirreciones"></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="Provincias" asp-action="Consulta">Provincias</a></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="Municipios" asp-action="Consulta">Municipios</a></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="DistritosMunicipales" asp-action="Consulta">DistritosMunicipales</a></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="Sectores" asp-action="Consulta">Sectores</a></li>
                            <li class="divider"></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="Ventas" asp-action="Consulta">Ventas</a></li>
                            <li><a asp-area="" asp-controller="VentasDetalles" asp-action="Consulta">VentasDetalles</a></li>

                            <li class="divider"></li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-right">
                   @if (Context.Session.GetString("UsuarioId") != null)
                   {
                    <li><a asp-area="" asp-controller="Home" asp-action="CerrarSeccion">Salir de Session</a></li>

                   }
                   else
                   {
                    <li><a asp-area="" asp-controller="Home" asp-action="InicioSeccion">Inicio Session</a></li>

                   }

                  </ul>
            </div>


        </div>

    </nav>


    <div>
        <div>

            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; 2017 - FSVentasCoreAs</p>
                </footer>
            </div>
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>

</html>