FSVentasCoreAs/FSVentasCoreAs/Models/Proveedores.cs
using FSVentasCoreAs.Models.Dirreciones;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FSVentasCoreAs.Models
{
    public class Proveedores
    {
        [Key]
        public int ProveedorId { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = "Su Nombre Completo")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = "Marca  Articulo")]
        [ForeignKey("MarcasArticulos")]
        public int MarcaId { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = "Su Provincia")]
        [ForeignKey("Provincias")]
        public int ProvinciaId { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = " Su Municipio")]
        [ForeignKey("Municipios")]
        public int MunicipioId { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = " Su Distrito Municipal")]
        [ForeignKey("DistritosMunicipales")]
        public int DistritoId { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = " Su Paraje")]
        [ForeignKey("Sectores")]
        public int SectorId { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = "Su Direccion")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = "Su Numero Telefono ")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = "Su Numero de Fax")]
        public string Fax { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [Display(Name = "Su Correo Eletronico")]
        public string Correo { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy - mm - dd}", ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }
        public virtual MarcasArticulos MarcasArticulos { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual DistritosMunicipales DistritosMunicipales { get; set; }
        public virtual Sectores Sectores { get; set; }
    }
}

FSVentasCoreAs/FSVentasCoreAs/Controllers/ProveedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FSVentasCoreAs.DAL;
using FSVentasCoreAs.Models;
using Microsoft.AspNetCore.Authorization;
using FSVentasCoreAs.Models.Dirreciones;
using FSVentasCoreAs.BLL;

namespace FSVentasCoreAs.Controllers
{
    [Authorize(ActiveAuthenticationSchemes = "CookiePolicy")]
    public class ProveedoresController : Controller
    {
        private readonly FSVentasCoreDb _context;
        private FSVentasCoreDb db = new FSVentasCoreDb();

        public ProveedoresController(FSVentasCoreDb context)
        {
            _context = context;    
        }
        public async Task<IActionResult> Index()
        {
            var fSVentasCoreDb = _context.Proveedores.Include(p => p.DistritosMunicipales).Include(p => p.MarcasArticulos).Include(p => p.Municipios).Include(p => p.Provincias).Include(p => p.Sectores);
            return View(await fSVentasCoreDb.ToListAsync());
        }

        // GET: Proveedores
        public async Task<IActionResult> Consulta()
        {
            var fSVentasCoreDb = _context.Proveedores.Include(p => p.DistritosMunicipales).Include(p => p.MarcasArticulos).Include(p => p.Municipios).Include(p => p.Provincias).Include(p => p.Sectores);
            return View(await fSVentasCoreDb.ToListAsync());
        }

        // GET: Proveedores/Details/5
        public async Task<IActionResult> Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedores = await _context.Proveedores
                .Include(p => p.DistritosMunicipales)
                .Include(p => p.MarcasArticulos)
                .Include(p => p.Municipios)
                .Include(p => p.Provincias)
                .Include(p => p.Sectores)
                .SingleOrDefaultAsync(m => m.ProveedorId == id);
            if (proveedores == null)
            {
                return NotFound();
            }

            return View(proveedores);
        }

        // GET: Proveedores/Create
        public IActionResult Crear()
        {
            List<Provincias> lstProvincia = db.Provincias.ToList();
            lstProvincia.Insert(0, new Provincias { ProvinciaId = 0, Nombre = "--Select Provincia--" });
            ViewBag.ProvinciaId = new SelectList(lstProvincia, "ProvinciaId", "Nombre");
            List<Municipios> lstMunicipios = db.Municipios.ToList();
            ViewBag.MunicipioId = new SelectList(lstMunicipios, "MunicipioId", "Nombre");
            List<DistritosMunicipales> lstDistrito = db.DistritosMunicipales.ToList();
            ViewBag.DistritoId = new SelectList(lstDistrito, "DistritoId", "Nombre");
            List<Sectores> lstSectores = db.Sectores.ToList();
            ViewBag.SectorId = new SelectList(lstSectores, "SectorId", "Nombre");
            return View();
        }

        // POST: Proveedores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear([Bind("ProveedorId,Nombre,MarcaId,ProvinciaId,MunicipioId,DistritoId,SectorId,Direccion,Telefono,Fax,Correo,Fecha")] Proveedores proveedores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proveedores);
                await _context.SaveChangesAsync();
                return RedirectToAction("Consulta");
            }
            ViewData["DistritoId"] = new SelectList(_context.DistritosMunicipales, "DistritoId", "Nombre", proveedores.DistritoId);
            ViewData["MarcaId"] = new SelectList(_context.MarcasArticulos, "MarcaId", "Nombre", proveedores.MarcaId);
            ViewData["MunicipioId"] = new SelectList(_context.Municipios, "MunicipioId", "Nombre", proveedores.MunicipioId);
            ViewData["ProvinciaId"] = new SelectList(_context.Provincias, "ProvinciaId", "Nombre", proveedores.ProvinciaId);
            ViewData["SectorId"] = new SelectList(_context.Sectores, "SectorId", "Nombre", proveedores.SectorId);
            return View(proveedores);
        }
        public JsonResult GetMunicipiosByProvinciaId(int id)
        {
            List<Municipios> municipios = new List<Municipios>();
            if (id > 0)
            {
                municipios = db.Municipios.Where(p => p.ProvinciaId == id).ToList();


            }
            else
            {
                municipios.Insert(0, new Municipios { MunicipioId = 0, Nombre = "--Selecionar Municipios --" });
            }
            var result = (from r in municipios
                          select new
                          {
                              municipioId = r.MunicipioId,
                              nombre = r.Nombre
                          }).ToList();

            return Json(result);

            // return Json(result);

        }

        public JsonResult GetdistritoIdByMunicipioId(int id)
        {
            List<DistritosMunicipales> distrito = new List<DistritosMunicipales>();
            if (id > 0)
            {
                distrito = db.DistritosMunicipales.Where(p => p.MunicipioId == id).ToList();

            }
            else
            {
                distrito.Insert(0, new DistritosMunicipales { DistritoId = 0, Nombre = "--Seleccionar Distritos Municipales--" });
            }
            var result = (from r in distrito
                          select new
                          {
                              distritoId = r.DistritoId,
                              nombre = r.Nombre
                          }).ToList();

            return Json(result);
            // return Json(result);

        }
        public JsonResult GetSectoresIdByDistritoId(int id)
        {
            List<Sectores> sectores = new List<Sectores>();
            if (id > 0)
            {
                sectores = db.Sectores.Where(p => p.DistritoId == id).ToList();

            }
            else
            {
                sectores.Insert(0, new Sectores { SectorId = 0, Nombre = "--Selecionar  sectores " });
            }
            var result = (from r in sectores
                          select new
                          {
                              sectorId = r.SectorId,
                              nombre = r.Nombre
                          }).ToList();

            return Json(result);
            // return Json(result);

        }


        // GET: Proveedores/Edit/5
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedores = await _context.Proveedores.SingleOrDefaultAsync(m => m.ProveedorId == id);
            if (proveedores == null)
            {
                return NotFound();
            }
            ViewData["DistritoId"] = new SelectList(_context.DistritosMunicipales, "DistritoId", "Nombre", proveedores.DistritoId);
            ViewData["MarcaId"] = new SelectList(_context.MarcasArticulos, "MarcaId", "Nombre", proveedores.MarcaId);
            ViewData["MunicipioId"] = new SelectList(_context.Municipios, "MunicipioId", "Nombre", proveedores.MunicipioId);
            ViewData["ProvinciaId"] = new SelectList(_context.Provincias, "ProvinciaId", "Nombre", proveedores.ProvinciaId);
            ViewData["SectorId"] = new SelectList(_context.Sectores, "SectorId", "Nombre", proveedores.SectorId);
            return View(proveedores);
        }

        // POST: Proveedores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, [Bind("ProveedorId,Nombre,MarcaId,ProvinciaId,MunicipioId,DistritoId,SectorId,Direccion,Telefono,Fax,Correo,Fecha")] Proveedores proveedores)
        {
            if (id != proveedores.ProveedorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proveedores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProveedoresExists(proveedores.ProveedorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Consulta");
            }
            ViewData["DistritoId"] = new SelectList(_context.DistritosMunicipales, "DistritoId", "Nombre", proveedores.DistritoId);
            ViewData["MarcaId"] = new SelectList(_context.MarcasArticulos, "MarcaId", "Nombre", proveedores.MarcaId);
            ViewData["MunicipioId"] = new SelectList(_context.Municipios, "MunicipioId", "Nombre", proveedores.MunicipioId);
            ViewData["ProvinciaId"] = new SelectList(_context.Provincias, "ProvinciaId", "Nombre", proveedores.ProvinciaId);
            ViewData["SectorId"] = new SelectList(_context.Sectores, "SectorId", "Nombre", proveedores.SectorId);
            return View(proveedores);
        }

        // GET: Proveedores/Delete/5
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedores = await _context.Proveedores
                .Include(p => p.DistritosMunicipales)

FSVentasCoreAs/FSVentasCoreAs/Views/Proveedores/Consulta.cshtml
@model IEnumerable<FSVentasCoreAs.Models.Proveedores>

@{
    ViewData["Title"] = "Consulta";
}

<h2>Consulta Proveedores</h2>

<p>
    <a asp-action="Crear">Crer</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Direccion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefono)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fax)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Correo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fecha)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.DistritosMunicipales)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MarcasArticulos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Municipios)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Provincias)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sectores)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DistritosMunicipales.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MarcasArticulos.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Municipios.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Provincias.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sectores.SectorId)
            </td>
            <td>
                <a asp-action="Editar" asp-route-id="@item.ProveedorId">Editar</a> |
                <a asp-action="Detalle" asp-route-id="@item.ProveedorId">Detalle</a> |
                <a asp-action="Eliminar" asp-route-id="@item.ProveedorId">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <a asp-action="Index">Reporte</a>
</div>

FSVentasCoreAs/FSVentasCoreAs/Views/Proveedores/Crear.cshtml
@model FSVentasCoreAs.Models.Proveedores

@{
    ViewData["Title"] = "Crear";
}

<h2>Crear</h2>


<form asp-action="Crear">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
    <script type="text/javascript">

        $(function () {
            if ($("#ProvinciaId").val() == '0') {
                var MunicipiosDefaultValue = "<option value='0'>--Seleccionar a Municipios --</option>";
                $("#MunicipioId").html(MunicipiosDefaultValue).show();

            }
            $(function () {
                if ($("#MunicipioId").val() == '0') {
                    var DistritoDefaultValue = "<option value='0'>--Seleccionar Distrito Municipal --</option>";
                    $("#DistritoId").html(DistritoDefaultValue).show();

                }
                $(function () {
                    if ($("#DistritoId").val() == '0') {
                        var ParajeDefaultValue = "<option value='0'>--Selecionar su Paraje--</option>";
                        $("#ParajeId").html(ParajeDefaultValue).show();

                    }

             $("#ProvinciaId").change(function () {
            var selectedItemValue = $(this).val();

            var ddlMunicipios = $("#MunicipioId");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetMunicipiosByProvinciaId", "Proveedores")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlMunicipios.html('');
                    $.each(data, function (id, option) {
                        ddlMunicipios.append($('<option></option>').val(option.municipioId).html(option.nombre));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load Municipios!.');
                }
            });
        });
        });
         $("#MunicipioId").change(function () {
            var selectedItemValue = $(this).val();

            var ddlDistrito = $("#DistritoId");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetdistritoIdByMunicipioId", "Proveedores")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlDistrito.html('');
                    $.each(data, function (id, option) {
                        ddlDistrito.append($('<option></option>').val(option.distritoId).html(option.nombre));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load Ciudad!.');
                }
            });
        });
            });
             $("#DistritoId").change(function () {
            var selectedItemValue = $(this).val();

            var ddlSectores = $("#SectorId");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetSectoresIdByDistritoId", "Proveedores")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlSectores.html('');
                    $.each(data, function (id, option) {
                        ddlSectores.append($('<option></option>').val(option.sectorId).html(option.nombre));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load Paraje!.');
                }
            });
        });
    });
    </script>
    <div class="form-horizontal">
        <h4>Proveedores</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Nombre" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MarcaId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="MarcaId" class ="form-control" asp-items="ViewBag.MarcaId"></select>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProvinciaId, "ProvinciaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProvinciaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProvinciaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MunicipioId, "MunicipioId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MunicipioId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MunicipioId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DistritoId, "Distrito Municipales", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DistritoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DistritoId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SectorId, "Sector", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SectorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SectorId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Direccion" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Telefono" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fax" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Correo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fecha" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Consulta">Ir a Lista</a>
</div>

FSVentasCoreAs/FSVentasCoreAs/Views/Proveedores/Detalle.cshtml
@model FSVentasCoreAs.Models.Proveedores

@{
    ViewData["Title"] = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Proveedores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DistritosMunicipales)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DistritosMunicipales.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MarcasArticulos)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MarcasArticulos.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Municipios)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Municipios.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Provincias)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Provincias.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sectores)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sectores.SectorId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Editar" asp-route-id="@Model.ProveedorId">Editar</a> |
    <a asp-action="Consulta">Ir a Lista</a>
</div>

FSVentasCoreAs/FSVentasCoreAs/Views/Proveedores/Editar.cshtml
@model FSVentasCoreAs.Models.Proveedores

@{
    ViewData["Title"] = "Editar";
}

<h2>Editar</h2>

<form asp-action="Editar">
    <div class="form-horizontal">
        <h4>Proveedores</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ProveedorId" />
        <div class="form-group">
            <label asp-for="Nombre" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MarcaId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="MarcaId" class="form-control" asp-items="ViewBag.MarcaId"></select>
                <span asp-validation-for="MarcaId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProvinciaId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ProvinciaId" class="form-control" asp-items="ViewBag.ProvinciaId"></select>
                <span asp-validation-for="ProvinciaId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MunicipioId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="MunicipioId" class="form-control" asp-items="ViewBag.MunicipioId"></select>
                <span asp-validation-for="MunicipioId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DistritoId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="DistritoId" class="form-control" asp-items="ViewBag.DistritoId"></select>
                <span asp-validation-for="DistritoId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SectorId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="SectorId" class="form-control" asp-items="ViewBag.SectorId"></select>
                <span asp-validation-for="SectorId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Direccion" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Telefono" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fax" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Correo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fecha" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Consulta">Ir a Lista</a>
</div>